# Generated by Django 2.2.7 on 2019-12-06 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UKI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='No_tic',
            new_name='No_of_ticket',
        ),
    ]
