# Generated by Django 2.2.6 on 2019-12-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UKI', '0003_auto_20191225_1549'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ticket',
            new_name='info',
        ),
    ]
